### ISSUE TITLE
Unable to publish to npm with github action

### ISSUE THREAD

**Issue by MattMcAdams** [MattMcAdams/stratus#32]
I'm getting the following error when running the github action to publish the package:
```
npm ERR! code E401
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/@mattmcadams%2fstratus - You must be logged in to publish packages.
```
The action code is as follows:
```yml
name: Publish package to NPM and Github Packages

on: 
  release:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I've made a token on npmjs and have added it to this repository's secrets with the name `NPM_TOKEN` and I'm not sure what else to do here.
